# Generated by Django 3.1.1 on 2020-09-15 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='profile_image',
            new_name='banner',
        ),
    ]
